version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Stardust-Development"
s3_bucket = "stardust-cloudformation-templates"
s3_prefix = ""
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "AppSyncAPILoggingLevel=\"ERROR\" UserPoolStackName=\"UserPool-Dev\""

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "Stardust-Production"
s3_bucket = "stardust-cloudformation-templates"
s3_prefix = ""
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "AppSyncAPILoggingLevel=\"ERROR\" UserPoolStackName=\"UserPool-Dev\""

[cognitostack]
[cognitostack.deploy]
[cognitostack.deploy.parameters]
stack_name = "UserPool-Dev"
s3_bucket = "stardust-cloudformation-templates"
s3_prefix = ""
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "SignInDomain=\"pv-degradation-pool-dev\""

[website.deploy.parameters]
stack_name = "Stardust-Website"
s3_bucket = "stardust-cloudformation-templates"
s3_prefix = ""
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = ""
