AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sets up the application stack for our hosted serverless PV Degradation Calculator

Parameters:
  AppSyncAPILoggingLevel:
    Type: String
    Description: The logging level for the GraphQL AppSync API.
    AllowedValues:
      - NONE
      - ERROR
      - ALL
  UserPoolStackName:
    Type: String
    Description: "The name of the stack that creates a User Pool of which to use for auth here. This stack must export
        a value named \"{StackName}-UserPoolID\""


Resources:
  IrradianceFuncIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": "lambda.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }
      Description: >
        The role that the IrradianceFunc Lambda Function will assume to allow execution and access to the dynamo table
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      PermissionsBoundary: "arn:aws:iam::502015339777:policy/StardustDevBoundary"
      Policies:
        - PolicyName: DynamoCachingTableAccess
          PolicyDocument: {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Sid": "Stmt1603872726428",
                "Action": [
                    "dynamodb:DeleteItem",
                    "dynamodb:GetItem",
                    "dynamodb:PutItem",
                    "dynamodb:Query",
                    "dynamodb:UpdateItem"
                ],
                "Effect": "Allow",
                "Resource": !GetAtt IrradianceCachingDynamoDBTable.Arn
              }
            ]
          }
      RoleName: !Sub "${AWS::StackName}-lambda-irradianceCalc"
  IrradianceFunc:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ../calculateIrradiance/
      Handler: index.handler
      Runtime: nodejs12.x
      Role: !GetAtt IrradianceFuncIAMRole.Arn
      Timeout: 7
      Environment:
        Variables:
          Caching_Table_Name: !Ref IrradianceCachingDynamoDBTable
  IrradianceAPRSFunc:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ../calculateAPRSIrradiance/
      Handler: index.handler
      Runtime: nodejs12.x
      Timeout: 10
      Role: !GetAtt IrradianceFuncIAMRole.Arn
      Environment:
        Variables:
          Caching_Table_Name: !Ref IrradianceCachingDynamoDBTable
  DegradationFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../calculatePVDegradation/
      Handler: index.handler
      Runtime: nodejs12.x
      PermissionsBoundary: "arn:aws:iam::502015339777:policy/StardustDevBoundary"
  IrradianceCachingDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: LatLon
          AttributeType: S
      KeySchema:
        - AttributeName: LatLon
          KeyType: HASH
      TableName: !Sub "${AWS::StackName}-IrradianceRequestsCache"
      TimeToLiveSpecification:
        AttributeName: ExpDate
        Enabled: true
  AppSyncAPIStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        AppSyncAPILoggingLevel: !Ref AppSyncAPILoggingLevel
        AppSyncLoggingExcludeVerbose: True
        UserPoolStack: !Ref UserPoolStackName
        IrradianceCalcLambdaFunctionArn: !GetAtt IrradianceFunc.Arn
        AprsIrradianceCalcLambdaFunctionArn: !GetAtt IrradianceAPRSFunc.Arn
        DegradationCalcLambdaFunctionArn: !GetAtt DegradationFunc.Arn
      TemplateURL: ./AppSyncStack.yaml
      TimeoutInMinutes: 10

Outputs:
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  IrradianceFunc:
    Description: "Calculate Irradiance Lambda Function ARN"
    Value: !GetAtt IrradianceFunc.Arn
  AprsIrradianceFunc:
    Description: "Calculate Irradiance from APRS Stations Lambda Function ARN"
    Value: !GetAtt IrradianceAPRSFunc.Arn
  DegradationFunc:
    Description: "Calculate Degradation Lambda Function ARN"
    Value: !GetAtt DegradationFunc.Arn
  AppSyncGraphQLURL:
    Description: The URL for the GraphQL API
    Value: !GetAtt AppSyncAPIStack.Outputs.AppSyncGraphQLURL
  AppSyncApiId:
    Description: The API ID for the AppSync API
    Value: !GetAtt AppSyncAPIStack.Outputs.AppSyncApiId

