#!/bin/bash
sam package -t "CloudFormationTemplates/template.yaml" --output-template-file "template-packaged.yaml" --s3-bucket "stardust-cloudformation-templates" --config-file "samconfig.toml" --config-env "default"
sam deploy -t "CloudFormationTemplates/template-packaged.yaml" --config-file "samconfig.toml" --config-env "default"