#!/bin/bash
sam package -t template.yaml --output-template-file "template-packaged.yaml" --s3-bucket "stardust-cloudformation-templates" --config-file "samconfig.toml" --config-env "default"
sam deploy -t template-packaged.yaml --s3-bucket "stardust-cloudformation-templates" --config-file "samconfig.toml" --config-env "default"
