version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Stardust-CalculateIrradiance"
s3_bucket = "stardust-cloudformation-templates"
s3_prefix = ""
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "AppSyncAPILoggingLevel=\"ERROR\" UserPoolStackName=\"UserPool-Dev\""

[cognitostack]
[cognitostack.deploy.parameters]
stack_name = "UserPool-Dev"
s3_bucket = "stardust-cloudformation-templates"
s3_prefix = ""
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "SignInDomain=\"pv-degradation-pool-dev\""

